project_name: go-turborepo-remote-cache

env:
  - SKIP_UPLOAD={{ if index .Env "SKIP_UPLOAD"  }}{{ .Env.SKIP_UPLOAD }}{{ else }}false{{ end }}

# Build step
builds:
  - id: go-turborepo-remote-cache
    main: .
    binary: bin/go-turborepo-remote-cache
    flags:
      - -trimpath
      - -tags=netgo
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# Publish step
release:
  mode: replace
  prerelease: auto

changelog:
  use: github
  disable: false

archives:
  - id: go-turborepo-remote-cache
    name_template: "go-turborepo-remote-cache-{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{.Arm }}{{ end }}"
    format: tar.gz
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
